export const doctors = [
  {
    id: 1,
    hisCode: "001",
    name: "Nguyễn Văn A",
    sex: 1,
    birthDate: "24/12/1887",
    account: "bs.nva",
    accountStatus: "active",
  },
  {
    id: 2,
    hisCode: "001",
    name: "Nguyễn Văn A",
    sex: 1,
    birthDate: "24/12/1887",
    account: "",
    accountStatus: "none",
  },
  {
    id: 3,
    hisCode: "001",
    name: "Nguyễn Thị A",
    sex: 0,
    birthDate: "24/12/1887",
    account: "bs.nva",
    accountStatus: "active",
  },
  {
    id: 4,
    hisCode: "001",
    name: "Nguyễn Văn A",
    sex: 1,
    birthDate: "24/12/1887",
    account: "",
    accountStatus: "none",
  },
  {
    id: 5,
    hisCode: "001",
    name: "Nguyễn Văn A",
    sex: 1,
    birthDate: "24/12/1887",
    account: "bs.nva",
    accountStatus: "disabled",
  },
  {
    id: 6,
    hisCode: "001",
    name: "Nguyễn Văn A",
    sex: 1,
    birthDate: "24/12/1887",
    account: "bs.nva",
    accountStatus: "active",
  },
  {
    id: 7,
    hisCode: "001",
    name: "Nguyễn Thị A",
    sex: 0,
    birthDate: "24/12/1887",
    account: "bs.nva",
    accountStatus: "active",
  },
  {
    id: 8,
    hisCode: "001",
    name: "Nguyễn Văn A",
    sex: 1,
    birthDate: "24/12/1887",
    account: "bs.nva",
    accountStatus: "active",
  },
  {
    id: 9,
    hisCode: "001",
    name: "Nguyễn Văn A",
    sex: 1,
    birthDate: "24/12/1887",
    account: "bs.nva",
    accountStatus: "active",
  },
  {
    id: 10,
    hisCode: "001",
    name: "Nguyễn Văn A",
    sex: 1,
    birthDate: "24/12/1887",
    account: "bs.nva",
    accountStatus: "active",
  },
];

export const nurses = [
  {
    id: 1,
    hisCode: "001",
    name: "Nguyễn Thị B",
    sex: 1,
    birthDate: "13/02/1888",
  },
  {
    id: 2,
    hisCode: "001",
    name: "Nguyễn Thị B",
    sex: 1,
    birthDate: "13/02/1888",
  },
  {
    id: 3,
    hisCode: "001",
    name: "Nguyễn Thị B",
    sex: 1,
    birthDate: "13/02/1888",
  },
  {
    id: 4,
    hisCode: "001",
    name: "Nguyễn Thị B",
    sex: 0,
    birthDate: "13/02/1888",
  },
  {
    id: 5,
    hisCode: "001",
    name: "Nguyễn Thị B",
    sex: 1,
    birthDate: "13/02/1888",
  },
  {
    id: 6,
    hisCode: "001",
    name: "Nguyễn Thị B",
    sex: 1,
    birthDate: "13/02/1888",
  },
  {
    id: 7,
    hisCode: "001",
    name: "Nguyễn Thị B",
    sex: 0,
    birthDate: "13/02/1888",
  },
  {
    id: 8,
    hisCode: "001",
    name: "Nguyễn Thị B",
    sex: 1,
    birthDate: "13/02/1888",
  },
  {
    id: 9,
    hisCode: "001",
    name: "Nguyễn Thị B",
    sex: 1,
    birthDate: "13/02/1888",
  },
  {
    id: 10,
    hisCode: "001",
    name: "Nguyễn Thị B",
    sex: 1,
    birthDate: "13/02/1888",
  },
];